name: time_planner
description: A beautiful, easy to use and customizable time planner for flutter mobile, desktop and web
version: 0.1.3

homepage: https://github.com/Jamalianpour/time_planner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
